apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  labels:
    tier: frontend
    type: application
spec:
  selector:
    matchLabels:
      app: client
  replicas: 1
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: nodejschess.azurecr.io/client:latest
        ports:
        - containerPort: 80

---
kind: Service
apiVersion: v1
metadata:
  name: client
spec:
  selector:
    app: client
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80